### ISSUE TITLE
Azure deployment and pipeline for Dashboard

### ISSUE THREAD

**Issue by sookah** [covidsimteam/prox-e#14]
Will be deploying for demo purposes.

the branch at `deployments/ui-dash`

The build:
- [x] Azure DevOps setup
- [x] Link repos
   - Created a new clone (azure)
   - [x] Move pipelines to present repo once verified(github) 
- [x] CI triggers
- [x] pipelines for dependencies, build/test
- [x] stage, archive and publish

The Release:
- [x] artifacts stages and release

Deployment:
- [x] prox-e-dash for dashboard app 
- [x] Azure blob for page hosting [ the app will replace the blob since blobs are not very feature rich for monitoring and diagnosing]

Sites:
https://proxedashstorage.z29.web.core.windows.net/

**Comment by sookah** [comment]
# Azure DevOps setup

The setup / project is now named prox-e

**Comment by sookah** [comment]
# Link repos

For test purposes and initial deployment the repo has been cloned as new repo in azure ops, once pipeline looks good we will make a yaml on the present github repo, this also mean i will not create a branch here.

**Comment by sookah** [comment]
# CI triggers

For now set to master

**Comment by sookah** [comment]
#  pipelines for dependencies, build/test

Following pipelines (for dashboard) and relative to the prox-e upper directory has been setup:

prox-e-dashboard CI > 
dashboard-CI > 
 - Install Deps
 - Test
 - Build

They are contained in their own scripts for more modularity

**Comment by sookah** [comment]
Issues:

postinstall scripts fails on clean install:
![image](https://user-images.githubusercontent.com/5146726/90165512-adda1080-dd90-11ea-837b-edf7de7f63b1.png)

Runs will fail too
![image](https://user-images.githubusercontent.com/5146726/90165629-da8e2800-dd90-11ea-86de-a4c20d192e47.png)

**Comment by sookah** [comment]
packages status

![image](https://user-images.githubusercontent.com/5146726/90176094-5cd21880-dda0-11ea-9dfc-4b8bd7b6ddee.png)

**Comment by sookah** [comment]
ok at this point this definitely also feels like .lock is not correct and in sync with package.json

the angular compiler is 9.1.12 where as package.json has 9.0.4 (caret)

**Comment by sookah** [comment]
![image](https://user-images.githubusercontent.com/5146726/90179943-2b5c4b80-dda6-11ea-834e-6279c571c5d1.png)

fixed with:
`npm install --save opencollective-postinstall`

**Comment by sookah** [comment]
![image](https://user-images.githubusercontent.com/5146726/90180343-bccbbd80-dda6-11ea-904a-7898f615a721.png)

**Comment by sookah** [comment]
feels like issue on my setup, with angular cli throwing the same error on a newly created project for the sake of finishing i will use the ops servers

**Comment by sookah** [comment]
failing on mixin for nb-auth
![image](https://user-images.githubusercontent.com/5146726/90188906-2bfbde80-ddb4-11ea-9019-4fede2f23e74.png)

**Comment by sookah** [comment]
build passing 

![image](https://user-images.githubusercontent.com/5146726/90190432-e42a8680-ddb6-11ea-888b-0d1eaa6853ae.png)

**Comment by sookah** [comment]
dist folder not being outputted

tested with clean build on gitpod and on azure
![image](https://user-images.githubusercontent.com/5146726/90196874-e5fb4680-ddc4-11ea-85aa-ddefd5f65ee0.png)

**Comment by sookah** [comment]
build seems to not be right further investigation is needed. We can also use deployment options from ng for azure

**Comment by risavkarna** [comment]
Just ran the older solution again and seems to work. Please check latest yml file on master for reference.

![done-2](https://user-images.githubusercontent.com/1485929/90209120-38128b00-de0a-11ea-869b-17d8799e512e.png)

**Comment by risavkarna** [comment]
The dist folder is set to `ui` directory on the root in `angular.json`. This probably needs to be created before the build artifacts are outputted there.

**Comment by sookah** [comment]
indeed, it must be this, the output path is ok to be in the dist folder, but if we want at build time to be at a different location, example for the ci with something like `--output-path=dist/dashboard` 

 also verified angular.json, tsconfig*

**Comment by sookah** [comment]
build/stage yaml so far

```yml
pool:
  name: Azure Pipelines
steps:
- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.x

- script: 'npm install'
  workingDirectory: hi/dashboard
  displayName: 'Install Deps'

- script: 'echo No tests to run for now'
  workingDirectory: hi/dashboard
  displayName: Test

- script: 'npm run build:prod'
  workingDirectory: hi/dashboard
  displayName: Build

- script: |
   find . -maxdepth 2 -type d -exec ls -ld "{}" \;
   
  workingDirectory: hi/dashboard
  displayName: 'list directory 2 level deep'

- task: CopyFiles@2
  displayName: 'Copy Dist'
  inputs:
    SourceFolder: hi/dashboard/dist
    TargetFolder: '{Build.ArtifactStagingDirectory}/dist'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.ArtifactStagingDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: dashboard'
  inputs:
    ArtifactName: dashboard
```
